# Generated by Django 2.2.2 on 2019-06-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bogoja', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bogoja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bogoja.Bogoja'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='bogoja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bogoja.Bogoja'),
        ),
    ]
