# Generated by Django 2.2.2 on 2019-06-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogoja', '0002_auto_20190628_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='bogoja',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
