# Generated by Django 2.2.2 on 2019-06-28 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bogoja', '0003_bogoja_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='BogojaProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='images/profiles')),
                ('profile_status', models.CharField(max_length=100)),
                ('bogoja', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
